"""Integration tests that exercise the model + analyzer pipeline.

These tests load the wav2vec2 model and use synthetic audio generated by
espeak-ng. They are marked as slow and can be skipped with ``-m "not slow"``.
"""

from __future__ import annotations

import io
import shutil
import subprocess
import tempfile

import numpy as np
import pytest

from src.analyzer import analyze
from src.articulatory import attach_tips
from src.audio import load_audio_file
from src.models import TARGET_SR, load_model, transcribe

SENTENCE = "The quick brown fox jumps over the lazy dog."


def _espeak_wav(text: str) -> np.ndarray:
    """Synthesize *text* to a 16kHz mono float32 array via espeak-ng + ffmpeg."""
    if not shutil.which("espeak-ng"):
        pytest.skip("espeak-ng not installed")

    with tempfile.NamedTemporaryFile(suffix=".wav", delete=False) as tmp:
        subprocess.run(
            ["espeak-ng", "-v", "en-us", text, "-w", tmp.name],
            check=True,
            capture_output=True,
        )
        return load_audio_file(tmp.name, samplerate=TARGET_SR)


@pytest.fixture(scope="module")
def model_fixture():
    processor, model, device = load_model()
    return processor, model


@pytest.mark.slow
class TestModelPipeline:
    def test_clean_pronunciation_scores_high(self, model_fixture):
        processor, model = model_fixture
        audio = _espeak_wav(SENTENCE)
        result = transcribe(audio, processor=processor, model=model)
        analysis = analyze(SENTENCE, result["tokens"])
        attach_tips(analysis)

        assert analysis["overall_score"] >= 0.85, (
            f"clean audio scored {analysis['overall_score']}: {result['raw']}"
        )
        for w in analysis["words"]:
            assert w["score"] >= 0.5, (
                f"word '{w['word']}' scored {w['score']} with errors {w['errors']}"
            )

    def test_first_word_not_destroyed_by_noise(self, model_fixture):
        """The first word should not accumulate spurious insertion errors."""
        processor, model = model_fixture
        audio = _espeak_wav(SENTENCE)
        result = transcribe(audio, processor=processor, model=model)
        analysis = analyze(SENTENCE, result["tokens"])

        first = analysis["words"][0]
        assert first["word"] == "The"
        insertion_count = sum(
            1 for e in first["errors"] if e["label"].startswith("extra sound")
        )
        assert insertion_count <= 1, (
            f"'The' had {insertion_count} insertions: {first['errors']}"
        )

    def test_analyzer_flags_known_errors_with_manual_tokens(self, model_fixture):
        """Verify error classification on a hand-crafted token sequence."""
        analysis = analyze("I really like rice.", ["aɪ", "l", "ɪ", "l", "i", "l", "aɪ", "k"])
        words = {w["word"]: w for w in analysis["words"]}
        assert words["really"]["score"] < 1.0
        assert any("R → L" in e["label"] for e in words["really"]["errors"])
